site_name: Vincent Archambault-Bouffard
site_description: Vincent Archambault-Bouffard - Professeur d'informatique au Collège de Maisonneuve.
site_url: https://archambaultv-prof.github.io/
theme:
  name: material
  language: fr
  features:
    - content.code.copy
    - navigation.top
    - navigation.footer
repo_url: https://github.com/archambaultv-prof/archambaultv-prof.github.io
copyright: Le contenu de ce site est sous licence <a href="https://creativecommons.org/licenses/by/4.0/deed.fr">CC-BY 4.0</a>.
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
# plugins: 
#   - social
